// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: examples.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExample = `-- name: CreateExample :exec
INSERT INTO examples (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
`

type CreateExampleParams struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) error {
	_, err := q.db.Exec(ctx, createExample,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getExampleForUpdate = `-- name: GetExampleForUpdate :one
SELECT id, name, created_at, updated_at
FROM examples
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetExampleForUpdate(ctx context.Context, id pgtype.UUID) (Example, error) {
	row := q.db.QueryRow(ctx, getExampleForUpdate, id)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExample = `-- name: UpdateExample :execrows
UPDATE examples
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateExampleParams struct {
	ID        pgtype.UUID
	Name      string
	UpdatedAt time.Time
}

func (q *Queries) UpdateExample(ctx context.Context, arg UpdateExampleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExample, arg.ID, arg.Name, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
