// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Example struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
