// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateExample(ctx context.Context, arg CreateExampleParams) error
	GetExampleForUpdate(ctx context.Context, id pgtype.UUID) (Example, error)
	UpdateExample(ctx context.Context, arg UpdateExampleParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
